In [38]:

# 1. Kütüphaneleri yükle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense

# 2. Eğitim veri setini yükle
train_dataset = pd.read_csv("iris_training.csv")

# 3. Girdi ve çıktıları belirle
X_train = train_dataset.iloc[:, 1:4].values
y_train = train_dataset.iloc[:, 4].values


#Eksik veri kontrolu? -yok

# 4. Eğitim veri setini özellik ölçeklendirme
sc_X_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)

# 5. Yapay Sinir Ağı Oluşturma
model = Sequential()
model.add(Dense(units=20, kernel_initializer='uniform', activation='relu', input_dim=3))
model.add(Dense(units=10, activation='relu', kernel_initializer='uniform'))  # Yeni gizli katman
model.add(Dense(units=5, activation='relu', kernel_initializer='uniform'))
model.add(Dense(units=3, activation='softmax', kernel_initializer='uniform'))


model.summary()

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 6. Modeli eğitme
model.fit(X_train, y_train, epochs=80, batch_size=10)

# 7. Test veri setini yükle
test_dataset = pd.read_csv("iris_test.csv")

# 8. Girdi ve çıktıları belirle
X_test = test_dataset.iloc[:, 1:4].values
y_test = test_dataset.iloc[:, 4].values

# 9. Test veri setini özellik ölçeklendirme
X_test = sc_X_train.transform(X_test)

# 10. Modeli test etme
y_pred = model.predict(X_test)
y_pred2 = np.argmax(y_pred, axis=1)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred2)
print("Confusion Matrix'i:")
print(cm)

test_accuracy = np.sum(np.diag(cm)) / np.sum(cm)
print(f"Test Doğruluk: {test_accuracy}")

Model: "sequential_30"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_119 (Dense)           (None, 20)                80        
                                                                 
 dense_120 (Dense)           (None, 10)                210       
                                                                 
 dense_121 (Dense)           (None, 5)                 55        
                                                                 
 dense_122 (Dense)           (None, 3)                 18        
                                                                 
Total params: 363
Trainable params: 363
Non-trainable params: 0
_________________________________________________________________
Epoch 1/80
12/12 [==============================] - 0s 683us/step - loss: 1.0986 - accuracy: 0.3667
Epoch 2/80
12/12 [==============================] - 0s 748us/step - loss: 1.0981 - accu

12/12 [==============================] - 0s 1ms/step - loss: 0.1324 - accuracy: 0.9667
Epoch 74/80
12/12 [==============================] - 0s 958us/step - loss: 0.1267 - accuracy: 0.9667
Epoch 75/80
12/12 [==============================] - 0s 942us/step - loss: 0.1196 - accuracy: 0.9750
Epoch 76/80
12/12 [==============================] - 0s 1ms/step - loss: 0.1151 - accuracy: 0.9667
Epoch 77/80
12/12 [==============================] - 0s 929us/step - loss: 0.1099 - accuracy: 0.9667
Epoch 78/80
12/12 [==============================] - 0s 990us/step - loss: 0.1067 - accuracy: 0.9667
Epoch 79/80
12/12 [==============================] - 0s 799us/step - loss: 0.1021 - accuracy: 0.9667
Epoch 80/80
1/1 [==============================] - 0s 38ms/step
Confusion Matrix'i:
[[ 8  0  0]
 [ 0 13  1]
 [ 0  1  7]]
Test Doğruluk: 0.9333333333333333
